const country_codes = new Map();
country_codes.set("AFG", "Afghanistan");
country_codes.set("ALB", "Albania");
country_codes.set("ALG", "Algeria");
country_codes.set("AND", "Andorra");
country_codes.set("ANG", "Angola");
country_codes.set("ANT", "Antigua and Barbuda");
country_codes.set("ARG", "Argentina");
country_codes.set("ARM", "Armenia");
country_codes.set("ARU", "Aruba");
country_codes.set("ASA", "American Samoa");
country_codes.set("AUS", "Australia");
country_codes.set("AUT", "Austria");
country_codes.set("AZE", "Azerbaijan");
country_codes.set("BAH", "Bahamas");
country_codes.set("BAN", "Bangladesh");
country_codes.set("BAR", "Barbados");
country_codes.set("BDI", "Burundi");
country_codes.set("BEL", "Belgium");
country_codes.set("BEN", "Benin");
country_codes.set("BER", "Bermuda");
country_codes.set("BHU", "Bhutan");
country_codes.set("BIH", "Bosnia and Herzegovina");
country_codes.set("BIZ", "Belize");
country_codes.set("BLR", "Belarus");
country_codes.set("BOL", "Bolivia");
country_codes.set("BOT", "Botswana");
country_codes.set("BRA", "Brazil");
country_codes.set("BRN", "Bahrain");
country_codes.set("BRU", "Brunei");
country_codes.set("BUL", "Bulgaria");
country_codes.set("BUR", "Burkina Faso");
country_codes.set("CAF", "Central African Republic");
country_codes.set("CAM", "Cambodia");
country_codes.set("CAN", "Canada");
country_codes.set("CAY", "Cayman Islands");
country_codes.set("CGO", "Republic of the Congo");
country_codes.set("CHA", "Chad");
country_codes.set("CHI", "Chile");
country_codes.set("CHN", "China");
country_codes.set("CIV", "Ivory Coast");
country_codes.set("CMR", "Cameroon");
country_codes.set("COD", "Democratic Republic of the Congo");
country_codes.set("COK", "Cook Islands");
country_codes.set("COL", "Colombia");
country_codes.set("COM", "Comoros");
country_codes.set("CPV", "Cape Verde");
country_codes.set("CRC", "Costa Rica");
country_codes.set("CRO", "Croatia");
country_codes.set("CUB", "Cuba");
country_codes.set("CYP", "Cyprus");
country_codes.set("CZE", "Czechia");
country_codes.set("DEN", "Denmark");
country_codes.set("DJI", "Djibouti");
country_codes.set("DMA", "Dominica");
country_codes.set("DOM", "Dominican Republic");
country_codes.set("ECU", "Ecuador");
country_codes.set("EGY", "Egypt");
country_codes.set("ERI", "Eritrea");
country_codes.set("ESA", "El Salvador");
country_codes.set("ESP", "Spain");
country_codes.set("EST", "Estonia");
country_codes.set("ETH", "Ethiopia");
country_codes.set("FIJ", "Fiji");
country_codes.set("FIN", "Finland");
country_codes.set("FRA", "France");
country_codes.set("FRO", "Faroe Islands");
country_codes.set("FSM", "Federated States of Micronesia");
country_codes.set("GAB", "Gabon");
country_codes.set("GAM", "The Gambia");
country_codes.set("GBR", "Great Britain");
country_codes.set("GBS", "Guinea-Bissau");
country_codes.set("GEO", "Georgia");
country_codes.set("GEQ", "Equatorial Guinea");
country_codes.set("GER", "Germany");
country_codes.set("GHA", "Ghana");
country_codes.set("GRE", "Greece");
country_codes.set("GRN", "Grenada");
country_codes.set("GUA", "Guatemala");
country_codes.set("GUI", "Guinea");
country_codes.set("GUM", "Guam");
country_codes.set("GUY", "Guyana");
country_codes.set("HAI", "Haiti");
country_codes.set("HKG", "Hong Kong");
country_codes.set("HON", "Honduras");
country_codes.set("HUN", "Hungary");
country_codes.set("INA", "Indonesia");
country_codes.set("IND", "India");
country_codes.set("IRI", "Iran");
country_codes.set("IRL", "Ireland");
country_codes.set("IRQ", "Iraq");
country_codes.set("ISL", "Iceland");
country_codes.set("ISR", "Israel");
country_codes.set("ISV", "Virgin Islands");
country_codes.set("ITA", "Italy");
country_codes.set("IVB", "British Virgin Islands");
country_codes.set("JAM", "Jamaica");
country_codes.set("JOR", "Jordan");
country_codes.set("JPN", "Japan");
country_codes.set("KAZ", "Kazakhstan");
country_codes.set("KEN", "Kenya");
country_codes.set("KGZ", "Kyrgyzstan");
country_codes.set("KIR", "Kiribati");
country_codes.set("KOR", "South Korea");
country_codes.set("KOS", "Kosovo");
country_codes.set("KSA", "Saudi Arabia");
country_codes.set("KUW", "Kuwait");
country_codes.set("LAO", "Laos");
country_codes.set("LAT", "Latvia");
country_codes.set("LBA", "Libya");
country_codes.set("LBN", "Lebanon");
country_codes.set("LBR", "Liberia");
country_codes.set("LCA", "Saint Lucia");
country_codes.set("LES", "Lesotho");
country_codes.set("LIE", "Liechtenstein");
country_codes.set("LTU", "Lithuania");
country_codes.set("LUX", "Luxembourg");
country_codes.set("MAC", "Macau");
country_codes.set("MAD", "Madagascar");
country_codes.set("MAR", "Morocco");
country_codes.set("MAS", "Malaysia");
country_codes.set("MAW", "Malawi");
country_codes.set("MDA", "Moldova");
country_codes.set("MDV", "Maldives");
country_codes.set("MEX", "Mexico");
country_codes.set("MGL", "Mongolia");
country_codes.set("MHL", "Marshall Islands");
country_codes.set("MKD", "North Macedonia North Macedonia");
country_codes.set("MLI", "Mali");
country_codes.set("MLT", "Malta");
country_codes.set("MNE", "Montenegro");
country_codes.set("MON", "Monaco");
country_codes.set("MOZ", "Mozambique");
country_codes.set("MRI", "Mauritius");
country_codes.set("MTN", "Mauritania");
country_codes.set("MYA", "Myanmar");
country_codes.set("NAM", "Namibia");
country_codes.set("NCA", "Nicaragua");
country_codes.set("NED", "Netherlands");
country_codes.set("NEP", "Nepal");
country_codes.set("NGR", "Nigeria");
country_codes.set("NIG", "Niger");
country_codes.set("NOR", "Norway");
country_codes.set("NRU", "Nauru");
country_codes.set("NZL", "New Zealand");
country_codes.set("OMA", "Oman");
country_codes.set("PAK", "Pakistan");
country_codes.set("PAN", "Panama");
country_codes.set("PAR", "Paraguay");
country_codes.set("PER", "Peru");
country_codes.set("PHI", "Philippines");
country_codes.set("PLE", "Palestine");
country_codes.set("PLW", "Palau");
country_codes.set("PNG", "Papua New Guinea");
country_codes.set("POL", "Poland");
country_codes.set("POR", "Portugal");
country_codes.set("PRK", "North Korea");
country_codes.set("PUR", "Puerto Rico");
country_codes.set("QAT", "Qatar");
country_codes.set("ROU", "Romania");
country_codes.set("RSA", "South Africa");
country_codes.set("RUS", "Russia");
country_codes.set("RWA", "Rwanda");
country_codes.set("SAM", "Samoa");
country_codes.set("SEN", "Senegal");
country_codes.set("SEY", "Seychelles");
country_codes.set("SGP", "Singapore");
country_codes.set("SKN", "Saint Kitts and Nevis");
country_codes.set("SLE", "Sierra Leone");
country_codes.set("SLO", "Slovenia");
country_codes.set("SMR", "San Marino");
country_codes.set("SOL", "Solomon Islands");
country_codes.set("SOM", "Somalia");
country_codes.set("SRB", "Serbia");
country_codes.set("SRI", "Sri Lanka");
country_codes.set("SSD", "South Sudan");
country_codes.set("STP", "São Tomé and Príncipe");
country_codes.set("SUD", "Sudan");
country_codes.set("SUI", "Switzerland");
country_codes.set("SUR", "Suriname");
country_codes.set("SVK", "Slovakia");
country_codes.set("SWE", "Sweden");
country_codes.set("SWZ", "Eswatini Eswatini");
country_codes.set("SYR", "Syria");
country_codes.set("TAN", "Tanzania");
country_codes.set("TGA", "Tonga");
country_codes.set("THA", "Thailand");
country_codes.set("TJK", "Tajikistan");
country_codes.set("TKM", "Turkmenistan");
country_codes.set("TLS", "East Timor");
country_codes.set("TOG", "Togo");
country_codes.set("TPE", "Chinese Taipei");
country_codes.set("TTO", "Trinidad and Tobago");
country_codes.set("TUN", "Tunisia");
country_codes.set("TUR", "Turkey");
country_codes.set("TUV", "Tuvalu");
country_codes.set("UAE", "United Arab Emirates");
country_codes.set("UGA", "Uganda");
country_codes.set("UKR", "Ukraine");
country_codes.set("URU", "Uruguay");
country_codes.set("USA", "United States");
country_codes.set("UZB", "Uzbekistan");
country_codes.set("VAN", "Vanuatu");
country_codes.set("VEN", "Venezuela");
country_codes.set("VIE", "Vietnam");
country_codes.set("VIN", "Saint Vincent and the Grenadines");
country_codes.set("YEM", "Yemen");
country_codes.set("ZAM", "Zambia");
country_codes.set("ZIM", "Zimbabwe");

export default country_codes;